package domain.token;

public enum TokenType {
    SET, WORD, TEXT,
    PLUS, MINUS, STAR, EQ, LT, GT, EQEQ, LTEQ, GTEQ, EXCL, EXCLEQ, BAR, BARBAR, AMP, AMPAMP,
    LPAREN, RPAREN, LBRACE, RBRACE, COMMA,
    PRINT, IF, ELSE, WHILE, FOR, DO, BREAK, CONTINUE,
    EOF
}
